- name: Install RTLSDR requirements
  snap:
    name: "{{snaps}}"
    channel: beta
    state: present

- name: Setup links for RTLSDR libraries
  shell: |
    for p in `find /var/lib -name librtlsdr.pc`
    do
        ln -sf $p /usr/lib64/pkgconfig 
    done

    for p in `find /var/lib/snapd/snap/ -name librtlsdr* -not -path "*/pkgconfig/*"`
    do
        ln -sf $p /usr/lib64
    done

- name: Blacklist kernel RTL devices
  copy:
    dest: "/etc/modprobe.d/rtl-sdr-blacklist.conf" 
    content: |
        blacklist dvb_usb_rtl28xxu
        blacklist e4000
        blacklist rtl2832

- name: Test if dump1090 repo already exists
  stat: path="{{dump1090dir}}"
  register: status
  tags: dump1090

- name: Unzip dump1090 
  shell: |
    unzip -q -o -d "{{ dump1090dir }}" "{{ role_path }}/files/dump1090.zip"

- name: Install update Makefile to dump1090
  copy:
    src: Makefile
    dest: "{{dump1090dir}}"

- name: Compile dump1090
  shell: |
    cd "{{dump1090dir}}"
    make