- name: Add  Microsoft Linux Repo
  shell: |
    set timeout 3600
    curl -sSL "{{msrepo}}" | sudo tee "{{msrepofile}}"
    curl -sSL "{{msrepogpg}}" > /tmp/microsoft.asc
    rpm --import /tmp/microsoft.asc

- name: Install dnf package manager
  yum:
    name: dnf
    state: present
  
- name: Install Packages
  dnf: 
    name: "{{ packages }}"
    state: present

- name: Enable and Start snapd service
  service:
    name: snapd
    state: started
    enabled: yes

- name: Enable user for sudo access
  lineinfile: 
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\t+ALL='
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
 
- name: Stop and Disable FirewallD
  service: 
    name: firewalld
    state: stopped
    enabled: no

- name: Enable Snapd service
  service: 
    name: snapd
    state: started
    enabled: yes

- name: Add net.ipv4.conf.all.rp_filter to /etc/sysctl.conf
  lineinfile: 
    path: /etc/sysctl.conf
    state: present
    line: 'net.ipv4.conf.all.rp_filter = 0'
    insertafter: EOF

- name: Add fs.inotify.max_user_watches to /etc/sysctl.conf
  lineinfile: 
    path: /etc/sysctl.conf
    state: present
    line: 'fs.inotify.max_user_watches = 16384'
    insertafter: EOF

- name: Update system sysctl variables
  command: sysctl --system